#
# Exercise 4 - Matrix Multiply
# AUTHORS  Günther Schindler
#	   Klaus Naumann
#          Alexander Schnapp
#
#
CC = gcc
CFLAGS = -Wall

matrixmultiply :
	gcc $(CFLAGS)	main.c \
			matrix_multiply.c \
			time_measurement.c \
			-o matrixmultiply

clean :
	rm -f 	matrixmultiply \
		$(DOCUNAME).aux $(DOCUNAME).log $(DOCUNAME).pdf $(DOCUNAME).toc
